from pygame import Rect

# Scale, Refresh Rate (30 Hz)
SCALE = 2
REFRESH_RATE = 30

# The width and height of the game window
WINDOW_WIDTH = 800*SCALE
WINDOW_HEIGHT = 800*SCALE

# The visual padding for the outer game board
HORIZONTAL_PADDING = 100*SCALE
VERTICAL_PADDING = 50*SCALE

# The number of ranks and files
N_VERTICAL_TILES = 9
N_HORIZONTAL_TILES = 8

# The size of each tile
VERTICAL_TILE_SIZE = (WINDOW_HEIGHT - 2 * VERTICAL_PADDING) / N_VERTICAL_TILES
HORIZONTAL_TILE_SIZE = (WINDOW_WIDTH - 2 * HORIZONTAL_PADDING) / N_HORIZONTAL_TILES

# The board's rectangle
BOARD_LEFT = HORIZONTAL_PADDING
BOARD_WIDTH = WINDOW_WIDTH-2*HORIZONTAL_PADDING
BOARD_TOP = VERTICAL_PADDING
BOARD_HEIGHT = WINDOW_HEIGHT-2*VERTICAL_PADDING

GAME_BOARD_RECTANGLE = Rect(BOARD_LEFT, BOARD_TOP, BOARD_WIDTH, BOARD_HEIGHT)

# Line thickness
OUTER_LINE_THICKNESS = 5*SCALE
INNER_LINE_THICKNESS = 5*SCALE

# Colors
LINE_COLOR = (0, 0, 0)
BACKGROUND_COLOR = (255, 165, 0)
